"""
HTTP Request logging middleware module.

Assigns a unique identifier to every incoming HTTP request and logs a summary
line for the request and response. It measures the total request duration and
flags slow requests to aid in performance monitoring.
"""

import logging
import time
import uuid

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request

from app.core.log_context import request_id_ctx

logger = logging.getLogger(__name__)


class RequestLoggingMiddleware(BaseHTTPMiddleware):
    """
    Middleware that logs incoming HTTP requests and their responses.

    Intercepts every HTTP request, assigns a short UUID as the request ID,
    sets it in the context variable for subsequent loggers, and measures the
    time taken to process the request. Injects the request ID into response headers.
    """

    async def dispatch(self, request: Request, call_next):
        """
        Process the request, log its lifecycle, and measure execution time.

        Args:
            request (Request): The incoming Starlette HTTP request.
            call_next (Callable): The next middleware or route handler in the chain.

        Returns:
            Response: The HTTP response generated by the application.

        Raises:
            Exception: Re-raises any unhandled exceptions occurring during request processing.
        """
        request_id = str(uuid.uuid4())[:8]
        request_id_ctx.set(request_id)

        start = time.perf_counter()
        logger.info("[REQUEST] --> %s %s", request.method, request.url.path)

        try:
            response = await call_next(request)
        except Exception:
            logger.exception(
                "[REQUEST] Unhandled exception during %s %s",
                request.method,
                request.url.path,
            )
            raise

        duration_ms = (time.perf_counter() - start) * 1000
        marker = "SLOW " if duration_ms >= 500 else ""
        logger.info(
            "[REQUEST] <-- %s%s %s status=%s TOTAL=%.1fms",
            marker,
            request.method,
            request.url.path,
            response.status_code,
            duration_ms,
        )

        response.headers["X-Request-ID"] = request_id
        return response
