"""Add sales_orders, sales_order_items, backorders table

Revision ID: 39edbc11938c
Revises: 6bf92a649033
Create Date: 2026-07-09 18:19:36.095873

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "39edbc11938c"
down_revision: Union[str, Sequence[str], None] = "6bf92a649033"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
