"""update backorder table

Revision ID: 760faa595b7e
Revises: 72ff10ba716d
Create Date: 2026-07-13 12:37:56.421795

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "760faa595b7e"
down_revision: Union[str, Sequence[str], None] = "72ff10ba716d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "backorders", "sales_order_item_id", new_column_name="sales_order_id"
    )
    op.create_index(
        op.f("ix_backorders_product_id"), "backorders", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_backorders_sales_order_id"),
        "backorders",
        ["sales_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_backorders_warehouse_id"), "backorders", ["warehouse_id"], unique=False
    )
    op.drop_constraint(
        op.f("backorders_sales_order_item_id_fkey"), "backorders", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "backorders", "sales_orders", ["sales_order_id"], ["id"]
    )
    op.create_index(
        op.f("ix_customers_organization_id"),
        "customers",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_product_id"), "inventory", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_warehouse_id"), "inventory", ["warehouse_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_transactions_created_by"),
        "inventory_transactions",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_product_id"),
        "inventory_transactions",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_transactions_warehouse_id"),
        "inventory_transactions",
        ["warehouse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_organizations_action_by"), "organizations", ["action_by"], unique=False
    )
    op.create_index(
        op.f("ix_product_suppliers_product_id"),
        "product_suppliers",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_suppliers_supplier_id"),
        "product_suppliers",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_products_category_id"), "products", ["category_id"], unique=False
    )
    op.create_index(
        op.f("ix_products_organization_id"),
        "products",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_items_po_id"),
        "purchase_order_items",
        ["po_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_order_items_product_id"),
        "purchase_order_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_approved_by"),
        "purchase_orders",
        ["approved_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_created_by"),
        "purchase_orders",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_destination_warehouse_id"),
        "purchase_orders",
        ["destination_warehouse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_purchase_orders_supplier_id"),
        "purchase_orders",
        ["supplier_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_product_id"),
        "sales_order_items",
        ["product_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_order_items_sales_order_id"),
        "sales_order_items",
        ["sales_order_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_orders_created_by"), "sales_orders", ["created_by"], unique=False
    )
    op.create_index(
        op.f("ix_sales_orders_customer_id"),
        "sales_orders",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sales_orders_source_warehouse_id"),
        "sales_orders",
        ["source_warehouse_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_suppliers_organization_id"),
        "suppliers",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_users_organization_id"), "users", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_warehouse_users_assigned_by"),
        "warehouse_users",
        ["assigned_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_warehouse_users_user_id"), "warehouse_users", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_warehouse_users_user_id"), table_name="warehouse_users")
    op.drop_index(op.f("ix_warehouse_users_assigned_by"), table_name="warehouse_users")
    op.drop_index(op.f("ix_users_organization_id"), table_name="users")
    op.drop_index(op.f("ix_suppliers_organization_id"), table_name="suppliers")
    op.drop_index(
        op.f("ix_sales_orders_source_warehouse_id"), table_name="sales_orders"
    )
    op.drop_index(op.f("ix_sales_orders_customer_id"), table_name="sales_orders")
    op.drop_index(op.f("ix_sales_orders_created_by"), table_name="sales_orders")
    op.drop_index(
        op.f("ix_sales_order_items_sales_order_id"), table_name="sales_order_items"
    )
    op.drop_index(
        op.f("ix_sales_order_items_product_id"), table_name="sales_order_items"
    )
    op.drop_index(op.f("ix_purchase_orders_supplier_id"), table_name="purchase_orders")
    op.drop_index(
        op.f("ix_purchase_orders_destination_warehouse_id"),
        table_name="purchase_orders",
    )
    op.drop_index(op.f("ix_purchase_orders_created_by"), table_name="purchase_orders")
    op.drop_index(op.f("ix_purchase_orders_approved_by"), table_name="purchase_orders")
    op.drop_index(
        op.f("ix_purchase_order_items_product_id"), table_name="purchase_order_items"
    )
    op.drop_index(
        op.f("ix_purchase_order_items_po_id"), table_name="purchase_order_items"
    )
    op.drop_index(op.f("ix_products_organization_id"), table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(
        op.f("ix_product_suppliers_supplier_id"), table_name="product_suppliers"
    )
    op.drop_index(
        op.f("ix_product_suppliers_product_id"), table_name="product_suppliers"
    )
    op.drop_index(op.f("ix_organizations_action_by"), table_name="organizations")
    op.drop_index(
        op.f("ix_inventory_transactions_warehouse_id"),
        table_name="inventory_transactions",
    )
    op.drop_index(
        op.f("ix_inventory_transactions_product_id"),
        table_name="inventory_transactions",
    )
    op.drop_index(
        op.f("ix_inventory_transactions_created_by"),
        table_name="inventory_transactions",
    )
    op.drop_index(op.f("ix_inventory_warehouse_id"), table_name="inventory")
    op.drop_index(op.f("ix_inventory_product_id"), table_name="inventory")
    op.drop_index(op.f("ix_customers_organization_id"), table_name="customers")
    op.alter_column(
        "backorders", "sales_order_id", new_column_name="sales_order_item_id"
    )
    op.drop_constraint(None, "backorders", type_="foreignkey")
    op.create_foreign_key(
        op.f("backorders_sales_order_item_id_fkey"),
        "backorders",
        "sales_order_items",
        ["sales_order_item_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_backorders_warehouse_id"), table_name="backorders")
    op.drop_index(op.f("ix_backorders_sales_order_id"), table_name="backorders")
    op.drop_index(op.f("ix_backorders_product_id"), table_name="backorders")
    # ### end Alembic commands ###
