"""Initial schema

Revision ID: 834eff4b4410
Revises:
Create Date: 2026-07-17 10:22:56.519709

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "834eff4b4410"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
