"""update sales_order_types

Revision ID: b7de24e53f50
Revises: 760faa595b7e
Create Date: 2026-07-13 17:36:53.928286

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "b7de24e53f50"
down_revision: Union[str, Sequence[str], None] = "760faa595b7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
