"""make lastname of users optional

Revision ID: d1383df9ac90
Revises: 28ce1a63be98
Create Date: 2026-07-02 11:25:33.444369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d1383df9ac90"
down_revision: Union[str, Sequence[str], None] = "28ce1a63be98"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "last_name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
