"""Add Product Module

Revision ID: d5045fef7708
Revises: 78a4b9ea66c6
Create Date: 2026-07-03 14:59:27.477473

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5045fef7708"
down_revision: Union[str, Sequence[str], None] = "78a4b9ea66c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("unit", sa.String(length=20), server_default="pcs", nullable=True),
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("base_cost_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "base_selling_price", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            "is_perishable", sa.Boolean(), server_default="false", nullable=False
        ),
        sa.Column("shelf_life_days", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("active", "discontinued", "draft", name="product_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "sku", name="uq_product_org_sku"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("products")
    # ### end Alembic commands ###
