"""Add Inventory module

Revision ID: f624692d504e
Revises: bab4df4a9527
Create Date: 2026-07-06 10:55:47.776943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f624692d504e"
down_revision: Union[str, Sequence[str], None] = "bab4df4a9527"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column(
            "batch_number",
            sa.String(length=50),
            server_default="DEFAULT",
            nullable=False,
        ),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "reserved_quantity", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("reorder_level", sa.Integer(), server_default="0", nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "active",
                "expired",
                "depleted",
                "damaged",
                "quarantined",
                "disposed",
                name="inventory_status",
            ),
            server_default="active",
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("timezone('UTC', now())"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity >= 0", name="chk_inventory_quantity_positive"),
        sa.CheckConstraint(
            "reserved_quantity >= 0", name="chk_inventory_reserved_quantity_positive"
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "warehouse_id",
            "product_id",
            "batch_number",
            name="uq_inventory_warehouse_product_batch",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inventory")
    # ### end Alembic commands ###
