"""change colum name of shelf_life_days to shelf_life in product table

Revision ID: fa3d4f568b15
Revises: f624692d504e
Create Date: 2026-07-06 12:56:32.099484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa3d4f568b15"
down_revision: Union[str, Sequence[str], None] = "f624692d504e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("shelf_life", sa.Integer(), nullable=True))
    op.drop_column("products", "shelf_life_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column("shelf_life_days", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("products", "shelf_life")
    # ### end Alembic commands ###
